Fix typo: 'pluginError' -> 'PluginError'
This was causing a `TypeError` of `gutil.pluginError is not a function`,
rather than the intended error message.